BASE_URL = "https://api.wikitree.com/api.php"

DEFAULT_KEY = "Romanov-62"

GET_PROFILE = "getProfile"
GET_PERSON = "getPerson"
GET_BIO = "getBio"
GET_PHOTOS = "getPhotos"
GET_PEOPLE = "getPeople"
GET_ANCESTORS = "getAncestors"
GET_DESCENDANTS = "getDescendants"
GET_RELATIVES = "getRelatives"
GET_WATCHLIST = "getWatchlist"
GET_DNA_TESTS_BY_TEST_TAKER = "getDNATestsByTestTaker"
GET_CONNECTED_PROFILES_BY_DNA_TEST = "getConnectedProfilesByDNATest"
GET_CONNECTED_DNA_TESTS_BY_PROFILE = "getConnectedDNATestsByProfile"
GET_CATEGORIES = "getCategories"
SEARCH_PERSON = "searchPerson"
CLIENT_LOGIN = "clientLogin"
